ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CANCELLED_BY_DOCTOR';
ALTER TYPE "JobTaskType" ADD VALUE IF NOT EXISTS 'LLM_RETRY_POST_VISIT';
ALTER TYPE "JobTaskType" ADD VALUE IF NOT EXISTS 'SEND_CANCELLATION_EMAIL';