ALTER TABLE "Appointment" ADD COLUMN "calendarEventId" TEXT;
ALTER TYPE "JobTaskType" ADD VALUE IF NOT EXISTS 'SYNC_CALENDAR';
ALTER TYPE "JobTaskType" ADD VALUE IF NOT EXISTS 'CANCEL_CALENDAR';
ALTER TYPE "JobTaskType" ADD VALUE IF NOT EXISTS 'SEND_MEDICATION_REMINDER';